project: TodoExample
rootDir: "examples/TodoExample"
version: 0.1.0
author: "Santos Dumont"
type: "API" # api or batch
servers:
  - 8080

databases:
  type: sqlite3
  name: todo_example.db

models:
  POST:
    file:
      - "create_one.sql"
  GET:
    file:
      - "read_all.sql"
  PUT:
    file:
      - "update_one.sql"
  DELETE:
    file:
      - "delete_one.sql"
