### Create

POST http://127.0.0.1:8000/todos HTTP/1.1
Content-Type: application/json

{
    "title": "Seu Todo",
    "completed": true


}

### Read All

GET http://127.0.0.1:8000/todos HTTP/1.1

### Read One

GET http://127.0.0.1:8000/todos/11 HTTP/1.1

### Update One

PUT http://127.0.0.1:8000/todos/11 HTTP/1.1
Content-Type: application/json

{
    "title": "Novo Título2",
    "completed": true
}


### Delete One

DELETE http://127.0.0.1:8000/todos/11 HTTP/1.1

###